name: Release NATS

on:
    pull_request: 
        branches: 
            - 'feature/**'
        types: closed

jobs:
    Release_NATS:
        runs-on: ubuntu-latest
        if: ${{ github.event.pull_request.merged == true }}

        steps:
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: otpm/nats_jetstream_otpm:latest
